  services:
    ipfinder-dev:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      develop:
        watch:
          - action: sync
            path: .
            target: /app